AWSTemplateFormatVersion: "2010-09-09"

Description: |
  This CloudFormation template for testing macro

Metadata:
  AWS::CloudFormation::Interface:

    #Define user friendly Parameter Groups
    ParameterGroups:
      - Label:
          default: VPC Configuration
        Parameters:
          - pVPCId
          - pSubnetIds
          - pSecurityGroupIds

    #Define user friendly names for the parameters
    ParameterLabels:
      pVPCId:
        default: VPC Id
      pSubnetIds:
        default: Subnet Ids
      pSecurityGroupIds:
        default: Security Group Ids

Parameters:
  pVPCId:
    Description: |
      VPC Id of an existing VPC.
    Type: String

  pSubnetIds:
    Description: |
      Comma delimited list of existing Subnet Ids.
    Type: CommaDelimitedList

  pSecurityGroupIds:
    Description: |
      Comma delimited list of existing Security Group Ids.
    Type: CommaDelimitedList

Transform: ExpandVPCEndpoint

Resources:
  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002 #Using Transform to build ServiceName
            - E3003 #Using Transform to build ServiceName
    Properties:
      ExpandServiceCodes: ssm,ssmmessages,ec2,ec2messages
      VpcEndpointType: Interface
      VpcId: !Ref pVPCId
      PrivateDnsEnabled: true
      SubnetIds: !Ref pSubnetIds
      SecurityGroupIds: !Ref pSecurityGroupIds
