AWSTemplateFormatVersion: "2010-09-09"

Mappings:
  BucketMap:
    Monthly:
      ResourceName: MyThirtyDayBucket
      Retention: 30
    Yearly:
      Retention: 365

Transform: Explode

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: '!Explode Retention'
            Status: Enabled
    ExplodeMap: BucketMap

  NonExplodingBucket:
    Type: AWS::S3::Bucket
