AWSTemplateFormatVersion: "2010-09-09"

Description: Send data to Pardot from ferretone's form.

Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: get
