AWSTemplateFormatVersion: "2010-09-09"

Description: A simple NoSQL event database

Parameters:
  ReadCapacity:
    Description: Read Capacity Units
    Type: Number
    Default: 20

  WriteCapacity:
    Description: Write Capacity Units
    Type: Number
    Default: 20

Resources:
  Events:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: EventId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: EventId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacity
        WriteCapacityUnits: !Ref WriteCapacity

  EventQueue:
    Type: AWS::SQS::Queue

Outputs:
  EventTableARN:
    Description: ARN for the DynamoDB table
    Value: !GetAtt Events.Arn
